// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using MiniLibrary.Data;

#nullable disable

namespace MiniLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MiniLibrary.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id").HasColumnType("TEXT");
                    b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("TEXT");
                    b.Property<string>("DisplayName").HasColumnType("TEXT");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");
                    b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").HasColumnType("TEXT");
                    b.Property<string>("PhoneNumber").HasColumnType("TEXT");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");
                    b.Property<string>("SecurityStamp").HasColumnType("TEXT");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MiniLibrary.Models.Book", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Author").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<int>("AvailableCopies").HasColumnType("INTEGER");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<string>("Genre").HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("Isbn").HasMaxLength(50).HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<int>("TotalCopies").HasColumnType("INTEGER");
                    b.Property<int?>("Year").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.ToTable("Books");
                });

            modelBuilder.Entity("MiniLibrary.Models.BookLoan", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("BookId").HasColumnType("INTEGER");
                    b.Property<DateTime>("BorrowedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime?>("ReturnedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("BookId");
                    b.ToTable("BookLoans");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventAttendance", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("EventItemId").HasColumnType("INTEGER");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("EventItemId", "UserId").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("EventAttendances");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventInvitation", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("EventItemId").HasColumnType("INTEGER");
                    b.Property<string>("InviteeEmail").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<string>("InviteeUserId").HasColumnType("TEXT");
                    b.Property<string>("InviterId").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("RespondedAtUtc").HasColumnType("TEXT");
                    b.Property<DateTime>("SentAtUtc").HasColumnType("TEXT");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("EventItemId", "InviteeEmail").IsUnique();
                    b.HasIndex("InviteeUserId");
                    b.HasIndex("InviterId");
                    b.ToTable("EventInvitations");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("Category").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("TEXT");
                    b.Property<DateTime?>("EndAtUtc").HasColumnType("TEXT");
                    b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("OrganizerId").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("StartAtUtc").HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("OrganizerId");
                    b.ToTable("EventItems");
                });

            modelBuilder.Entity("MiniLibrary.Models.BookLoan", b =>
                {
                    b.HasOne("MiniLibrary.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventAttendance", b =>
                {
                    b.HasOne("MiniLibrary.Models.EventItem", "EventItem")
                        .WithMany("Attendees")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLibrary.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventItem");
                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventInvitation", b =>
                {
                    b.HasOne("MiniLibrary.Models.EventItem", "EventItem")
                        .WithMany("Invitations")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLibrary.Models.ApplicationUser", "InviteeUser")
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MiniLibrary.Models.ApplicationUser", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventItem");
                    b.Navigation("InviteeUser");
                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventItem", b =>
                {
                    b.HasOne("MiniLibrary.Models.ApplicationUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("MiniLibrary.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MiniLibrary.Models.EventItem", b =>
                {
                    b.Navigation("Attendees");
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
